import type { Merchant, Offer, OfferWithMerchant } from "@/lib/types";

export const merchants: Merchant[] = [
  {
    id: "vape-wholesale-usa",
    name: "Vape Wholesale USA",
    domain: "vapewholesaleusa.com",
    homepageUrl: "https://www.vapewholesaleusa.com",
    category: "Wholesale vape distributor",
    country: "US",
    supportsWholesale: true,
    requiresLicense: false,
    ageGatePresent: true,
    notes:
      "Las Vegas, NV based distributor. Carries disposable vapes, e-liquids, kits, and accessories. Reward program available. Free shipping on $3,000+.",
    freeShippingThreshold: 3000,
    minOrderValue: null,
    location: "Las Vegas, NV 89146",
    brands: ["AIMO", "3CHI", "Daze", "Air Bar", "Pyne Pod", "Coastal Clouds", "Yami Vapors"]
  },
  {
    id: "the-vape-mall",
    name: "The Vape Mall",
    domain: "thevapemall.com",
    homepageUrl: "https://www.thevapemall.com",
    category: "E-liquid & vape supplies wholesale",
    country: "US",
    supportsWholesale: true,
    requiresLicense: false,
    ageGatePresent: true,
    notes: "US-based e-liquid manufacturer and wholesaler. Offers custom e-juice blending. Free shipping on $65+.",
    freeShippingThreshold: 65,
    minOrderValue: null,
    location: "US",
    brands: ["The Vape Mall"]
  },
  {
    id: "flawless-vape-shop",
    name: "Flawless Vape Shop",
    domain: "flawlessvapeshop.com",
    homepageUrl: "https://www.flawlessvapeshop.com",
    category: "Vape retailer & wholesaler",
    country: "US",
    supportsWholesale: true,
    requiresLicense: false,
    ageGatePresent: true,
    notes:
      "Large US retailer with loyalty rewards program. Free shipping on $100+. Newsletter signup gives 10% off first order. Clearance up to 80% off.",
    freeShippingThreshold: 100,
    minOrderValue: null,
    location: "US",
    brands: ["Voopoo", "SnowWolf", "Lost Vape", "Geek Vape"]
  },
  {
    id: "geek-vape",
    name: "Geek Vape",
    domain: "store.geekvape.com",
    homepageUrl: "https://store.geekvape.com",
    category: "Vape hardware manufacturer",
    country: "US",
    supportsWholesale: true,
    requiresLicense: false,
    ageGatePresent: true,
    notes:
      "Direct from manufacturer. Free shipping on $99+ (under 10 lbs). VIP program for $500+ orders. Bulk discounts on multiples.",
    freeShippingThreshold: 99,
    minOrderValue: null,
    location: "Oakland, CA",
    brands: ["Geek Vape", "Geek Bar"]
  },
  {
    id: "vapesourcing",
    name: "VapeSourcing",
    domain: "vapesourcing.com",
    homepageUrl: "https://www.vapesourcing.com",
    category: "Global vape distributor",
    country: "US/CN",
    supportsWholesale: true,
    requiresLicense: false,
    ageGatePresent: true,
    notes:
      "Global distributor with US warehouse. Free shipping on $95+. Frequent flash sales and product-specific coupon codes. Newsletter signup for 18% off first order.",
    freeShippingThreshold: 95,
    minOrderValue: null,
    location: "US / China",
    brands: ["SMOK", "Geek Vape", "Voopoo", "Lost Vape", "Uwell", "Eleaf"]
  },
  {
    id: "vaperanger",
    name: "VapeRanger",
    domain: "vaperanger.com",
    homepageUrl: "https://vaperanger.com",
    category: "Vape wholesale distributor",
    country: "US",
    supportsWholesale: true,
    requiresLicense: true,
    ageGatePresent: true,
    notes: "Wholesale-only distributor. Requires business account and tobacco license for most orders.",
    freeShippingThreshold: null,
    minOrderValue: null,
    location: "US",
    brands: ["Geek Bar", "Elf Bar", "Lost Mary", "EB Design"]
  },
  {
    id: "discount-vape-pen",
    name: "Discount Vape Pen",
    domain: "discountvapepen.com",
    homepageUrl: "https://discountvapepen.com",
    category: "Vape retailer",
    country: "US",
    supportsWholesale: false,
    requiresLicense: false,
    ageGatePresent: true,
    notes: "Retailer with frequent 10% off sitewide codes. Free shipping available.",
    freeShippingThreshold: null,
    minOrderValue: null,
    location: "US",
    brands: []
  },
  {
    id: "west-coast-vape-supply",
    name: "West Coast Vape Supply",
    domain: "westcoastvapesupply.com",
    homepageUrl: "https://westcoastvapesupply.com",
    category: "Vape retailer & wholesale",
    country: "US",
    supportsWholesale: true,
    requiresLicense: false,
    ageGatePresent: true,
    notes: "California-based. Regular promo codes and clearance events.",
    freeShippingThreshold: null,
    minOrderValue: null,
    location: "California, US",
    brands: ["Geek Vape", "SMOK", "Voopoo"]
  }
];

export const offers: Offer[] = [
  // === Vape Wholesale USA - Deals (from multiple coupon site reports, no explicit code revealed) ===
  {
    id: "vwusa-10-percent-sitewide",
    merchantId: "vape-wholesale-usa",
    offerType: "coupon_code",
    code: null,
    title: "10% off sitewide orders",
    description:
      "Reported sitewide discount. Multiple coupon sites list this as a current offer. Code is hidden behind 'reveal' buttons on partner sites.",
    discountValue: "10% off",
    minimumOrderValue: null,
    applicableProducts: "Sitewide",
    sourceUrl: "https://www.dontpayfull.com/at/vapewholesaleusa.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes:
      "DontPayFull reports 'Confirmed working by a shopper' but does not expose the code publicly. Treat as reported until verified at checkout.",
    sourceCount: 3
  },
  {
    id: "vwusa-15-percent-selected",
    merchantId: "vape-wholesale-usa",
    offerType: "coupon_code",
    code: null,
    title: "15% off selected products",
    description: "Reported discount on select premium vaping supplies. Offer varies by product category.",
    discountValue: "15% off",
    minimumOrderValue: null,
    applicableProducts: "Selected items",
    sourceUrl: "https://www.dontpayfull.com/at/vapewholesaleusa.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes: "Multiple coupon sites reference a 15% off selected items offer. Code not publicly exposed.",
    sourceCount: 2
  },
  {
    id: "vwusa-10-off-99",
    merchantId: "vape-wholesale-usa",
    offerType: "coupon_code",
    code: null,
    title: "10% off orders $99+",
    description: "Minimum order threshold discount for eligible purchases.",
    discountValue: "10% off",
    minimumOrderValue: 99,
    applicableProducts: "Eligible purchases over $99",
    sourceUrl: "https://www.dontpayfull.com/at/vapewholesaleusa.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes: "Listed on DontPayFull as '10% Off Any $99+ Purchase'.",
    sourceCount: 1
  },
  {
    id: "vwusa-bogo-pyne",
    merchantId: "vape-wholesale-usa",
    offerType: "bogo",
    code: null,
    title: "Buy 2 Get 1 Free — Pyne Pod 40K Kits",
    description: "Purchase two Pyne Pod 40K Kits and receive one free. Cannot be combined with other promotions.",
    discountValue: "Buy 2 Get 1 Free",
    minimumOrderValue: null,
    applicableProducts: "Pyne Pod 40K Kits",
    sourceUrl: "https://www.dontpayfull.com/at/vapewholesaleusa.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes: "Product-specific BOGO. Verified by shopper report on DontPayFull.",
    sourceCount: 1
  },
  {
    id: "vwusa-8-percent-members",
    merchantId: "vape-wholesale-usa",
    offerType: "automatic_discount",
    code: null,
    title: "8% off all orders for members",
    description: "Account holders may receive an automatic 8% discount on orders. Requires logged-in account.",
    discountValue: "8% off",
    minimumOrderValue: null,
    applicableProducts: "All orders",
    sourceUrl: "https://www.dontpayfull.com/at/vapewholesaleusa.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes: "DontPayFull lists as 'Verified by our staff' but no explicit code provided.",
    sourceCount: 1
  },
  {
    id: "vwusa-free-shipping",
    merchantId: "vape-wholesale-usa",
    offerType: "free_shipping",
    code: null,
    title: "Free shipping on $3,000+ orders",
    description:
      "Standard shipping is free for orders totaling $3,000 or more. Ships throughout the United States.",
    discountValue: "Free shipping",
    minimumOrderValue: 3000,
    applicableProducts: "All US orders",
    sourceUrl: "https://www.reediscount.com/vape-wholesale-usa/",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: "US domestic only",
    internalNotes: "Confirmed by multiple sources including ReeDiscount and SavingHeist.",
    sourceCount: 4
  },
  {
    id: "vwusa-rewards",
    merchantId: "vape-wholesale-usa",
    offerType: "reward",
    code: null,
    title: "Rewards credit for eligible wholesale orders",
    description:
      "Earn points on purchases. Store credit can be applied at checkout. Max credit coverage is 25% of order value per terms.",
    discountValue: "Store credit up to 25% of order",
    minimumOrderValue: null,
    applicableProducts: "Eligible wholesale purchases",
    sourceUrl: "https://www.vapewholesaleusa.com/reward-program",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-21",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes: "From official rewards page. Exact point conversion requires account login to verify."
  },
  {
    id: "vwusa-coastal-clouds-8",
    merchantId: "vape-wholesale-usa",
    offerType: "coupon_code",
    code: null,
    title: "8% off all Coastal Clouds products",
    description: "Brand-specific discount for Coastal Clouds e-liquids and products. Limited to one use per customer.",
    discountValue: "8% off",
    minimumOrderValue: null,
    applicableProducts: "Coastal Clouds brand only",
    sourceUrl: "https://www.dontpayfull.com/at/vapewholesaleusa.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: "Subject to seller verification and state restrictions",
    internalNotes: "Brand-specific code not publicly exposed.",
    sourceCount: 1
  },

  // === The Vape Mall - Codes with explicit values ===
  {
    id: "tvm-10offweel",
    merchantId: "the-vape-mall",
    offerType: "coupon_code",
    code: "10OFFWEEL",
    title: "15% off any order + free shipping",
    description: "Sitewide discount plus complimentary shipping on all qualifying orders.",
    discountValue: "15% off + free shipping",
    minimumOrderValue: null,
    applicableProducts: "Sitewide",
    sourceUrl: "https://www.reecoupons.com/view/the-vape-mall",
    sourceType: "coupon_site",
    confidence: "verified",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Cross-source verification (2026-05-23): ReeCoupons lists as 'Verified' 15% off any order + free shipping (Expire: Soon). Valuecom lists as 15% off Diy/Mint/Menthol + free shipping (Ends 05/24/2026). Coupert confirms 15% off Diy/Mint/Menthol. 3 independent coupon sites confirm this code is active. Discount description varies by landing page — likely 15% off with category variations. Verify at checkout before placing large orders.",
    sourceCount: 3
  },
  {
    id: "tvm-tysign10",
    merchantId: "the-vape-mall",
    offerType: "coupon_code",
    code: "TYSIGN10",
    title: "10% off sitewide + free shipping",
    description: "General sitewide discount with free shipping included.",
    discountValue: "10% off + free shipping",
    minimumOrderValue: null,
    applicableProducts: "Sitewide",
    sourceUrl: "https://www.reecoupons.com/view/the-vape-mall",
    sourceType: "coupon_site",
    confidence: "verified",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Cross-source verification (2026-05-23): ReeCoupons lists as 'Verified' 10% off sitewide + free shipping (Expire: Soon). Valuecom lists as $5 off orders over $30 + free shipping (Ends 05/24/2026). 2 independent sources confirm active status but descriptions conflict — likely code terms vary by landing page or changed recently. Treat as active but verify discount amount at checkout.",
    sourceCount: 2
  },
  {
    id: "tvm-greek",
    merchantId: "the-vape-mall",
    offerType: "coupon_code",
    code: "GREEK",
    title: "$5 off orders over $30 + free shipping",
    description: "Fixed amount discount with minimum purchase requirement.",
    discountValue: "$5 off",
    minimumOrderValue: 30,
    applicableProducts: "Orders $30+",
    sourceUrl: "https://www.reecoupons.com/view/the-vape-mall",
    sourceType: "coupon_site",
    confidence: "verified",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Cross-source verification (2026-05-23): ReeCoupons lists as 'Verified' $5 off orders over $30 + free shipping (Expire: Soon). Valuecom lists as '$20 OFF. Save $20 on All Items Above $150. Ends 05/25/2026'. 2 independent sources confirm active status but discount descriptions conflict significantly — likely code terms changed or vary by landing page. Treat as active but verify exact discount at checkout.",
    sourceCount: 2
  },
  {
    id: "tvm-sd565s",
    merchantId: "the-vape-mall",
    offerType: "coupon_code",
    code: "SD565S",
    title: "15% off everything + free shipping",
    description: "Universal sitewide discount with complimentary shipping.",
    discountValue: "15% off + free shipping",
    minimumOrderValue: null,
    applicableProducts: "Sitewide",
    sourceUrl: "https://www.reecoupons.com/view/the-vape-mall",
    sourceType: "coupon_site",
    confidence: "verified",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Cross-source verification (2026-05-23): ReeCoupons lists as 'Verified' 15% off everything + free shipping (Expire: Soon). Tenereteam reports 'Tested and valid' by staff. Valuecom confirms 'successfully applied on checkout page'. Coupert shows 'Save up to 5%' (Saved $1.05). Knoji marks as 'Likely to Work Today? No' from Jul 2025. 4 of 5 sources confirm active status; Knoji data is 11 months old. Strong consensus this code is active. Discount amount may vary by cart.",
    sourceCount: 5
  },
  {
    id: "tvm-free-shipping-65",
    merchantId: "the-vape-mall",
    offerType: "free_shipping",
    code: null,
    title: "Free shipping on $65+",
    description: "Complimentary shipping for orders meeting the minimum threshold.",
    discountValue: "Free shipping",
    minimumOrderValue: 65,
    applicableProducts: "Orders $65+",
    sourceUrl: "https://www.reecoupons.com/view/the-vape-mall",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "Standard shipping policy.",
    sourceCount: 1
  },

  // === Flawless Vape Shop ===
  {
    id: "fvs-service15",
    merchantId: "flawless-vape-shop",
    offerType: "coupon_code",
    code: "SERVICE15",
    title: "15% off storewide for members",
    description: "Members-only sitewide discount. Join the free loyalty program to qualify.",
    discountValue: "15% off",
    minimumOrderValue: null,
    applicableProducts: "Sitewide",
    sourceUrl: "https://flawlessvapeshop.valuecom.com/",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: "2026-05-24",
    requiresAccount: true,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Cross-source verification (2026-05-23): Tenereteam reports 'Tested and valid'. Valuecom confirms 'successfully applied on checkout page'. Reediscount marks 'Verified'. SimplyCodes shows 86 community verifications, last used 1w ago, members-only. DontPayFull lists as 'Expired Jan 22, 2026'. Misthub.valuecom lists as 10% off SALT NICOTINE with 'Ends 05/23/2026, 1 day left'. Highly conflicting — this code may have expired today or changed to category-specific. Treat as time-sensitive and verify immediately at checkout.",
    sourceCount: 6
  },
  {
    id: "fvs-newsletter-10",
    merchantId: "flawless-vape-shop",
    offerType: "coupon_code",
    code: null,
    title: "10% off first order — newsletter signup",
    description: "New subscribers receive a 10% discount code via email after registering on the website.",
    discountValue: "10% off",
    minimumOrderValue: null,
    applicableProducts: "First order only",
    sourceUrl: "https://www.slickdeals.net/promo-codes/flawless-vape-shop",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Evergreen offer. Code sent via email after subscription.",
    sourceCount: 2
  },
  {
    id: "fvs-free-shipping-100",
    merchantId: "flawless-vape-shop",
    offerType: "free_shipping",
    code: null,
    title: "Free shipping on $100+ domestic orders",
    description: "Free standard shipping on all domestic U.S. orders of $100 or more.",
    discountValue: "Free shipping",
    minimumOrderValue: 100,
    applicableProducts: "US domestic orders",
    sourceUrl: "https://www.slickdeals.net/promo-codes/flawless-vape-shop",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: "US domestic only",
    internalNotes: "Standard shipping policy confirmed by multiple sources.",
    sourceCount: 3
  },
  {
    id: "fvs-loyalty",
    merchantId: "flawless-vape-shop",
    offerType: "reward",
    code: null,
    title: "Loyalty rewards — 1 point per $1 spent",
    description: "Earn points on every purchase. Redeem 100 points for a $5 off coupon voucher.",
    discountValue: "$5 off per 100 points",
    minimumOrderValue: null,
    applicableProducts: "All purchases",
    sourceUrl: "https://www.slickdeals.net/promo-codes/flawless-vape-shop",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "Free loyalty program. Points convert to coupon vouchers.",
    sourceCount: 2
  },
  {
    id: "fvs-clearance",
    merchantId: "flawless-vape-shop",
    offerType: "clearance",
    code: null,
    title: "Clearance up to 80% off",
    description: "Premium e-liquids, discontinued hardware, and accessories at deep discounts.",
    discountValue: "Up to 80% off",
    minimumOrderValue: null,
    applicableProducts: "Clearance items",
    sourceUrl: "https://www.slickdeals.net/promo-codes/flawless-vape-shop",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "Ongoing clearance section.",
    sourceCount: 1
  },

  // === Geek Vape ===
  {
    id: "gv-free-shipping-99",
    merchantId: "geek-vape",
    offerType: "free_shipping",
    code: null,
    title: "Free shipping on $99+ (under 10 lbs)",
    description: "Free shipping for orders of $99 or more with total weight under 10 pounds. Ships within 2 business days via USPS or UPS.",
    discountValue: "Free shipping",
    minimumOrderValue: 99,
    applicableProducts: "Orders $99+ under 10 lbs",
    sourceUrl: "https://www.retailmenot.com/view/store.geekvape.com",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: "US domestic only",
    internalNotes: "Standard policy confirmed by RetailMeNot.",
    sourceCount: 2
  },
  {
    id: "gv-vip",
    merchantId: "geek-vape",
    offerType: "reward",
    code: null,
    title: "VIP program — $500 minimum order",
    description: "Frequent buyers can join the VIP program for extra checkout discounts. Minimum $500 order required.",
    discountValue: "Extra VIP discounts",
    minimumOrderValue: 500,
    applicableProducts: "All orders",
    sourceUrl: "https://www.retailmenot.com/view/store.geekvape.com",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "VIP tier requires $500 minimum.",
    sourceCount: 1
  },
  {
    id: "gv-bulk-10",
    merchantId: "geek-vape",
    offerType: "automatic_discount",
    code: null,
    title: "10% off when buying multiples",
    description: "Automatic discount when ordering multiples of the same product (e.g., pods or tanks).",
    discountValue: "10% off",
    minimumOrderValue: null,
    applicableProducts: "Multiples of same SKU",
    sourceUrl: "https://www.retailmenot.com/view/store.geekvape.com",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "Bulk auto-discount.",
    sourceCount: 1
  },
  {
    id: "gv-exit-5",
    merchantId: "geek-vape",
    offerType: "coupon_code",
    code: null,
    title: "5% off first order — exit intent",
    description: "A popup often appears when leaving the site offering 5% off your first order.",
    discountValue: "5% off",
    minimumOrderValue: null,
    applicableProducts: "First order",
    sourceUrl: "https://www.retailmenot.com/view/store.geekvape.com",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Exit-intent popup offer.",
    sourceCount: 1
  },

  // === VapeSourcing ===
  {
    id: "vs-22off-129",
    merchantId: "vapesourcing",
    offerType: "coupon_code",
    code: null,
    title: "22% off purchases of $129+",
    description: "Sitewide percentage discount with minimum order threshold.",
    discountValue: "22% off",
    minimumOrderValue: 129,
    applicableProducts: "Sitewide",
    sourceUrl: "https://www.coupons.com/coupon-codes/vape-sourcing",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Coupons.com lists as verified working. Code hidden.",
    sourceCount: 1
  },
  {
    id: "vs-18off-first",
    merchantId: "vapesourcing",
    offerType: "coupon_code",
    code: null,
    title: "18% off first order with email signup",
    description: "New customers only. Subscribe to the newsletter to receive the discount code.",
    discountValue: "18% off",
    minimumOrderValue: null,
    applicableProducts: "First order",
    sourceUrl: "https://www.coupons.com/coupon-codes/vape-sourcing",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Newsletter signup required. Code sent via email.",
    sourceCount: 2
  },
  {
    id: "vs-free-shipping-95",
    merchantId: "vapesourcing",
    offerType: "free_shipping",
    code: null,
    title: "Free shipping on $95+",
    description: "Complimentary shipping for qualifying orders.",
    discountValue: "Free shipping",
    minimumOrderValue: 95,
    applicableProducts: "Orders $95+",
    sourceUrl: "https://www.coupons.com/coupon-codes/vape-sourcing",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "Standard policy.",
    sourceCount: 2
  },
  {
    id: "vs-referral-25",
    merchantId: "vapesourcing",
    offerType: "coupon_code",
    code: null,
    title: "25% off with friend referrals",
    description: "Invite friends. When they buy, you receive 20% off your next purchase.",
    discountValue: "20% off next order",
    minimumOrderValue: null,
    applicableProducts: "Referral reward",
    sourceUrl: "https://www.coupons.com/coupon-codes/vape-sourcing",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Referral program. Friend must complete purchase.",
    sourceCount: 1
  },

  // === VapeRanger ===
  {
    id: "vr-wholesale-account",
    merchantId: "vaperanger",
    offerType: "automatic_discount",
    code: null,
    title: "Wholesale pricing — business account required",
    description: "True wholesale distributor. Requires approved business account and tobacco license for most orders.",
    discountValue: "Wholesale pricing",
    minimumOrderValue: null,
    applicableProducts: "All products",
    sourceUrl: "https://vaperanger.com",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: true,
    requiresLicense: true,
    stackable: null,
    stateRestrictions: "State restrictions apply",
    internalNotes: "Wholesale-only. License verification required.",
    sourceCount: 1
  },

  // === Discount Vape Pen ===
  {
    id: "dvp-10-sitewide",
    merchantId: "discount-vape-pen",
    offerType: "coupon_code",
    code: null,
    title: "10% off sitewide",
    description: "General percentage discount available periodically.",
    discountValue: "10% off",
    minimumOrderValue: null,
    applicableProducts: "Sitewide",
    sourceUrl: "https://discountvapepen.com",
    sourceType: "coupon_site",
    confidence: "reported",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: false,
    stateRestrictions: null,
    internalNotes: "Code not publicly exposed.",
    sourceCount: 1
  },

  // === West Coast Vape Supply ===
  {
    id: "wcvs-promo",
    merchantId: "west-coast-vape-supply",
    offerType: "sale",
    code: null,
    title: "Regular promo codes and clearance events",
    description: "California-based retailer with frequent sales and promotional codes.",
    discountValue: "Varies",
    minimumOrderValue: null,
    applicableProducts: "Varies",
    sourceUrl: "https://westcoastvapesupply.com",
    sourceType: "official",
    confidence: "official",
    lastCheckedAt: "2026-05-23",
    expiresAt: null,
    requiresAccount: false,
    requiresLicense: false,
    stackable: null,
    stateRestrictions: null,
    internalNotes: "Check site for current promos.",
    sourceCount: 1
  }
];

export const getOffersWithMerchants = (): OfferWithMerchant[] =>
  offers
    .map((offer) => ({
      ...offer,
      merchant: merchants.find((merchant) => merchant.id === offer.merchantId) ?? merchants[0]
    }))
    .sort((a, b) => confidenceRank(a.confidence) - confidenceRank(b.confidence));

export const getMerchantById = (id: string) => merchants.find((merchant) => merchant.id === id);

export const getOffersByMerchantId = (merchantId: string): OfferWithMerchant[] =>
  getOffersWithMerchants().filter((offer) => offer.merchantId === merchantId);

const confidenceOrder = {
  verified: 0,
  official: 1,
  reported: 2,
  expired: 3
};

export const confidenceRank = (confidence: Offer["confidence"]) => confidenceOrder[confidence];

export const updatedAt = "2026-05-23";

export const faqItems: { question: string; answer: string }[] = [
  {
    question: "Do I need a wholesale license to buy from Vape Wholesale USA?",
    answer:
      "According to publicly available FAQ information, individual buyers do not need an additional license to purchase from Vape Wholesale USA. However, some dedicated wholesale distributors like VapeRanger do require a tobacco license and approved business account. Always check the specific merchant's requirements before ordering."
  },
  {
    question: "What is the minimum order for free shipping at Vape Wholesale USA?",
    answer:
      "Vape Wholesale USA offers free standard shipping on orders of $3,000 or more within the United States. This is a high threshold designed for true wholesale buyers. For smaller orders, compare alternatives like The Vape Mall ($65+) or Flawless Vape Shop ($100+)."
  },
  {
    question: "Are these coupon codes verified to work?",
    answer:
      "We classify every offer by confidence level. 'Official' offers come from the merchant's own site or program. 'Reported' offers come from third-party coupon sites and have not been independently verified at checkout. We never publish codes we know are expired."
  },
  {
    question: "Can I stack multiple coupon codes on a single order?",
    answer:
      "Most vape retailers, including Flawless Vape Shop, allow only one coupon code per order. Vape Wholesale USA also states that offers cannot be combined with other promotions. Always read the terms before checkout."
  },
  {
    question: "How do I get the best wholesale vape discounts?",
    answer:
      "For the deepest discounts: 1) Join loyalty programs (Flawless Vape Shop, Geek Vape VIP), 2) Sign up for newsletters to get first-order codes, 3) Buy in bulk for automatic multi-unit discounts, 4) Check clearance sections for up to 80% off, and 5) Use our savings calculator to compare real value after shipping."
  },
  {
    question: "Is Vape Wholesale USA legit?",
    answer:
      "Vape Wholesale USA has been operating in the US market for over ten years and is based in Las Vegas, NV. They accept major credit cards (Visa, MasterCard, Discover) and ship throughout the United States. As with any vape purchase, buyers should verify age requirements (21+) and check their state's specific regulations."
  }
];
